version: '3.7'

services:
  crontab-ui:
    build: .
    image: ghcr.io/povilasid/crontab-ui-docker:main
    network_mode: bridge
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
